import { Job, JobSeekerProfile } from '../types/jobs';

export const DEMO_JOBS: Job[] = [
  {
    id: '1',
    title: 'Software Developer',
    company: 'Navkar Technologies',
    companyLogo: undefined,
    location: 'Surat, Gujarat',
    type: 'full-time',
    salary: '6-10 LPA',
    salaryMin: 600000,
    salaryMax: 1000000,
    experience: '2-4 years',
    description: 'Looking for skilled software developers with expertise in React and Node.js to build scalable web applications.',
    requirements: ['React.js', 'Node.js', 'MongoDB', 'TypeScript', 'REST APIs'],
    education: 'B.Tech / MCA',
    workMode: 'hybrid',
    industry: 'IT',
    companySize: '50-100',
    benefits: ['PF', 'Health Insurance', 'Festival Bonus', 'Flexible Hours'],
    skills: ['React.js', 'Node.js', 'MongoDB', 'TypeScript'],
    postedAt: '2 days ago',
    deadline: '2026-03-15',
    isActive: true,
    isVerified: true,
    contactEmail: 'hr@navkartech.com',
    openings: 3,
  },
  {
    id: '2',
    title: 'Chartered Accountant',
    company: 'Jain & Associates',
    location: 'Ahmedabad, Gujarat',
    type: 'full-time',
    salary: '8-12 LPA',
    salaryMin: 800000,
    salaryMax: 1200000,
    experience: '3-5 years',
    description: 'Seeking a qualified CA for our growing practice. GST and Income Tax expertise required.',
    requirements: ['CA Qualified', 'GST Filing', 'Income Tax', 'Audit', 'Tally'],
    education: 'CA',
    workMode: 'onsite',
    industry: 'Finance',
    companySize: '10-50',
    benefits: ['PF', 'ESIC', 'Performance Bonus'],
    skills: ['GST', 'Income Tax', 'Audit', 'Tally'],
    postedAt: '5 days ago',
    deadline: '2026-03-20',
    isActive: true,
    isVerified: true,
    contactPhone: '9876543210',
    openings: 1,
  },
  {
    id: '3',
    title: 'Event Decorator',
    company: 'Mahavir Decorators',
    location: 'Mumbai, Maharashtra',
    type: 'full-time',
    salary: '3-5 LPA',
    salaryMin: 300000,
    salaryMax: 500000,
    experience: '1-3 years',
    description: 'Creative event decorator needed for wedding and corporate events.',
    requirements: ['Balloon Decoration', 'Event Planning', 'Flower Arrangement', 'Creative Design'],
    education: '12th Pass or above',
    workMode: 'onsite',
    industry: 'Event',
    companySize: '10-50',
    benefits: ['Travel Allowance', 'Festival Bonus', 'Accommodation for outstation events'],
    skills: ['Balloon Decoration', 'Event Planning', 'Flower Arrangement'],
    postedAt: '1 day ago',
    isActive: true,
    isVerified: false,
    contactEmail: 'careers@mahavirdecor.com',
    openings: 5,
  },
  {
    id: '4',
    title: 'Diamond Assorter',
    company: 'Parshwa Gems',
    location: 'Surat, Gujarat',
    type: 'full-time',
    salary: '4-6 LPA',
    salaryMin: 400000,
    salaryMax: 600000,
    experience: '1-3 years',
    description: 'Experienced diamond assorter needed for our export unit.',
    requirements: ['Diamond Sorting', 'Quality Check', 'Export Documentation'],
    education: '10th Pass or above',
    workMode: 'onsite',
    industry: 'Manufacturing',
    companySize: '100+',
    skills: ['Diamond Sorting', 'Quality Check'],
    postedAt: '3 days ago',
    isActive: true,
    isVerified: true,
    openings: 2,
  },
  {
    id: '5',
    title: 'Social Media Manager',
    company: 'Tirthankar Digital',
    location: 'Remote',
    type: 'part-time',
    salary: '15-20K/month',
    experience: 'Fresher',
    description: 'Manage social media for Jain community organizations and businesses.',
    requirements: ['Instagram', 'Facebook', 'Content Creation', 'Canva', 'Analytics'],
    education: 'Graduate',
    workMode: 'remote',
    industry: 'Marketing',
    companySize: '1-10',
    skills: ['Social Media', 'Content Creation', 'Canva'],
    postedAt: '1 week ago',
    isActive: true,
    isVerified: false,
    contactEmail: 'hiring@tirthankardigital.com',
    openings: 2,
  },
];

export const DEMO_SEEKER_PROFILE: JobSeekerProfile = {
  id: 's1',
  name: 'Rajesh Shah',
  currentStatus: 'working',
  totalExperience: '3 years',
  currentCompany: 'InfoTech Solutions',
  currentSalary: '5 LPA',
  expectedSalary: '8 LPA',
  preferredLocation: ['Surat', 'Ahmedabad'],
  preferredType: 'full-time',
  education: [
    { qualification: 'B.Tech', course: 'Computer Science', college: 'SVNIT', passingYear: '2021' },
  ],
  experience: [
    { company: 'InfoTech Solutions', role: 'Software Developer', duration: '2021 - Present', responsibilities: 'Full stack development' },
  ],
  skills: [
    { name: 'React.js', proficiency: 'advanced' },
    { name: 'Node.js', proficiency: 'intermediate' },
    { name: 'Python', proficiency: 'intermediate' },
  ],
  immediateJoiner: false,
  noticePeriod: '30 days',
  willingToTravel: true,
};
