import { MaharajProfile, MaharajPlanner, MaharajEvent, MaharajContact } from '../types/maharaj';

export const DEMO_MAHARAJ_PROFILES: MaharajProfile[] = [
  {
    id: '1',
    nameEn: 'Acharya Shri Chandrasagarji Maharaj Saheb',
    nameGu: 'આચાર્ય શ્રી ચંદ્રસાગરજી મહારાજ સાહેબ',
    dikshaName: 'Chandrasagar',
    sampraday: 'Shwetambar',
    gachchh: 'Tapagachchh',
    guruName: 'Acharya Shri Suryasagarji Maharaj',
    dikshaDate: '1995-03-15',
    dikshaPlace: 'Palitana',
    sanghId: 'S1',
    sanghName: 'Shri Chandrasagar Sangh',
    sanghMemberCount: 12,
    isLeader: true,
    isPublic: true,
    followersCount: 15200,
    isFollowing: false,
    currentLocation: {
      city: 'Ahmedabad',
      area: 'Paldi',
      upashrayName: 'Shri Jain Shwetambar Murtipujak Sangh',
      fromDate: '2026-02-10',
      toDate: '2026-03-15',
      lastUpdatedAt: '2026-02-19',
      status: 'updated_today',
    },
    schedule: {
      pravachanTime: '8:30 AM - 10:00 AM',
      samayikTime: '6:00 AM',
      pratikramanTime: '6:30 PM',
      swadhyayTime: '4:00 PM - 5:00 PM',
      notes: 'Youth swadhyay every Saturday at 11:00 AM',
    },
  },
  {
    id: '2',
    nameEn: 'Sadhviji Shri Divyaprabha Maharaj',
    nameGu: 'સાધ્વીજી શ્રી દિવ્યપ્રભા મહારાજ',
    dikshaName: 'Divyaprabha',
    sampraday: 'Shwetambar',
    gachchh: 'Tapagachchh',
    guruName: 'Sadhviji Shri Chandanprabha Maharaj',
    dikshaDate: '2005-11-20',
    dikshaPlace: 'Surat',
    sanghId: 'S2',
    sanghName: 'Shri Divyaprabha Sangh',
    sanghMemberCount: 8,
    isLeader: true,
    isPublic: true,
    followersCount: 8500,
    isFollowing: true,
    currentLocation: {
      city: 'Surat',
      area: 'Varachha',
      upashrayName: 'Shri Jain Sangh Varachha',
      fromDate: '2026-02-05',
      toDate: '2026-02-25',
      lastUpdatedAt: '2026-02-18',
      status: 'updated_this_week',
    },
    schedule: {
      pravachanTime: '9:00 AM - 10:30 AM',
      samayikTime: '5:30 AM',
      pratikramanTime: '7:00 PM',
    },
  },
  {
    id: '3',
    nameEn: 'Muni Shri Ratnakarji Maharaj',
    nameGu: 'મુનિ શ્રી રત્નાકરજી મહારાજ',
    dikshaName: 'Ratnakar',
    sampraday: 'Shwetambar',
    gachchh: 'Khartar',
    guruName: 'Acharya Shri Padmasagarji Maharaj',
    dikshaDate: '2010-06-10',
    dikshaPlace: 'Jaipur',
    isPublic: true,
    followersCount: 5600,
    isFollowing: false,
    currentLocation: {
      city: 'Rajkot',
      area: 'Kalavad Road',
      upashrayName: 'Shri Jain Derasar Trust',
      fromDate: '2026-01-20',
      lastUpdatedAt: '2026-02-10',
      status: 'outdated',
    },
    schedule: {
      pravachanTime: '8:00 AM - 9:30 AM',
      pratikramanTime: '6:00 PM',
    },
  },
  {
    id: '4',
    nameEn: 'Acharya Shri Bhuvanbhanusagarji Maharaj',
    nameGu: 'આચાર્ય શ્રી ભુવનભાનુસાગરજી મહારાજ',
    dikshaName: 'Bhuvanbhanusagar',
    sampraday: 'Shwetambar',
    gachchh: 'Tapagachchh',
    guruName: 'Acharya Shri Hemchandrasagarji Maharaj',
    dikshaDate: '1998-01-26',
    dikshaPlace: 'Mumbai',
    sanghId: 'S3',
    sanghName: 'Shri Bhuvanbhanu Sangh',
    sanghMemberCount: 15,
    isLeader: true,
    isPublic: true,
    followersCount: 22000,
    currentLocation: {
      city: 'Mumbai',
      area: 'Ghatkopar',
      upashrayName: 'Shri Jain Shwetambar Sangh Ghatkopar',
      fromDate: '2026-02-01',
      toDate: '2026-04-30',
      lastUpdatedAt: '2026-02-19',
      status: 'updated_today',
    },
    schedule: {
      pravachanTime: '7:30 AM - 9:00 AM',
      samayikTime: '5:00 AM',
      pratikramanTime: '6:30 PM',
      swadhyayTime: '3:30 PM - 4:30 PM',
      notes: 'Special tapasya guidance on Sundays',
    },
  },
  {
    id: '5',
    nameEn: 'Sadhviji Shri Sudarshana Maharaj',
    nameGu: 'સાધ્વીજી શ્રી સુદર્શના મહારાજ',
    dikshaName: 'Sudarshana',
    sampraday: 'Sthanakvasi',
    guruName: 'Sadhviji Shri Prabhavati Maharaj',
    dikshaDate: '2008-09-05',
    dikshaPlace: 'Ahmedabad',
    isPublic: true,
    followersCount: 4200,
    currentLocation: {
      city: 'Vadodara',
      area: 'Alkapuri',
      upashrayName: 'Sthanakvasi Jain Upashray',
      fromDate: '2026-02-12',
      lastUpdatedAt: '2026-02-17',
      status: 'updated_this_week',
    },
    schedule: {
      pravachanTime: '9:00 AM - 10:00 AM',
      pratikramanTime: '6:00 PM',
      swadhyayTime: '4:00 PM',
    },
  },
];

export const DEMO_MAHARAJ_PLANNERS: Record<string, MaharajPlanner> = {
  '1': {
    tomorrow: {
      date: '2026-02-20',
      city: 'Ahmedabad',
      area: 'Paldi',
      upashray: 'Shri Jain Shwetambar Murtipujak Sangh',
      status: 'confirmed',
      notes: 'Special pravachan on Mahavir Jayanti preparations',
    },
    weekly: [
      { date: '2026-02-20', city: 'Ahmedabad', area: 'Paldi', upashray: 'Shri Jain Sangh', status: 'confirmed' },
      { date: '2026-02-21', city: 'Ahmedabad', area: 'Paldi', upashray: 'Shri Jain Sangh', status: 'confirmed' },
      { date: '2026-02-22', city: 'Ahmedabad', area: 'Navrangpura', upashray: 'Navrangpura Sangh', status: 'tentative' },
      { date: '2026-02-23', city: 'Ahmedabad', area: 'Navrangpura', upashray: 'Navrangpura Sangh', status: 'tentative' },
      { date: '2026-02-24', city: 'Ahmedabad', area: 'Satellite', upashray: 'Satellite Jain Derasar', status: 'tentative' },
    ],
    monthly: [
      { city: 'Ahmedabad', fromDate: '2026-02-10', toDate: '2026-03-15', event: 'Chaturmas preparation' },
      { city: 'Gandhinagar', fromDate: '2026-03-16', toDate: '2026-03-25' },
      { city: 'Mehsana', fromDate: '2026-03-26', toDate: '2026-04-10', event: 'Mahavir Jayanti celebrations' },
    ],
  },
  '4': {
    tomorrow: {
      date: '2026-02-20',
      city: 'Mumbai',
      area: 'Ghatkopar',
      upashray: 'Shri Jain Shwetambar Sangh Ghatkopar',
      status: 'confirmed',
    },
    weekly: [
      { date: '2026-02-20', city: 'Mumbai', area: 'Ghatkopar', status: 'confirmed' },
      { date: '2026-02-21', city: 'Mumbai', area: 'Ghatkopar', status: 'confirmed' },
      { date: '2026-02-22', city: 'Mumbai', area: 'Mulund', upashray: 'Mulund Jain Sangh', status: 'tentative' },
      { date: '2026-02-23', city: 'Mumbai', area: 'Mulund', status: 'tentative' },
    ],
    monthly: [
      { city: 'Mumbai', fromDate: '2026-02-01', toDate: '2026-04-30', event: 'Extended stay for community events' },
    ],
  },
};

export const DEMO_MAHARAJ_EVENTS: Record<string, MaharajEvent[]> = {
  '1': [
    { id: 'e1', title: 'Special Pravachan: Path of Ahimsa', description: 'A 3-day series on practicing ahimsa in modern life', eventDate: '2026-02-22', location: 'Paldi Sangh, Ahmedabad', type: 'pravachan' },
    { id: 'e2', title: 'Youth Swadhyay Session', description: 'Interactive session for youth aged 15-30', eventDate: '2026-02-23', location: 'Paldi Sangh, Ahmedabad', type: 'other' },
    { id: 'e3', title: 'Atthai Tap Guidance', description: 'Guidance for devotees doing 8-day tap', eventDate: '2026-03-01', location: 'Paldi Sangh, Ahmedabad', type: 'tap' },
  ],
  '2': [
    { id: 'e4', title: 'Women Empowerment through Dharma', description: 'Special pravachan series for women', eventDate: '2026-02-21', location: 'Varachha Sangh, Surat', type: 'pravachan' },
  ],
  '4': [
    { id: 'e5', title: 'Mahavir Jayanti Grand Celebration', description: 'Community-wide celebration with procession', eventDate: '2026-04-10', location: 'Ghatkopar, Mumbai', type: 'mahotsav' },
    { id: 'e6', title: 'Seva Camp', description: 'Free health checkup and blood donation', eventDate: '2026-02-25', location: 'Ghatkopar Sangh, Mumbai', type: 'seva' },
  ],
};

export const DEMO_MAHARAJ_CONTACTS: Record<string, MaharajContact[]> = {
  '1': [
    { id: 'c1', personName: 'Kantibhai Shah', role: 'Sevak', phone: '+919876543210', whatsapp: '+919876543210', callingHours: '8 AM - 9 PM', isVerified: true },
    { id: 'c2', personName: 'Sureshbhai Mehta', role: 'Trust', phone: '+919876543211', callingHours: '10 AM - 6 PM', isVerified: true },
  ],
  '2': [
    { id: 'c3', personName: 'Pushpaben Jain', role: 'Sevak', phone: '+919876543212', whatsapp: '+919876543212', callingHours: '9 AM - 8 PM', isVerified: true },
  ],
  '4': [
    { id: 'c4', personName: 'Rajeshbhai Sanghvi', role: 'Trust', phone: '+919876543213', whatsapp: '+919876543213', callingHours: '9 AM - 7 PM', isVerified: true },
    { id: 'c5', personName: 'Nileshbhai Doshi', role: 'Sevak', phone: '+919876543214', callingHours: '8 AM - 9 PM', isVerified: true },
  ],
};
