import { MatrimonyProfile } from '../types/matrimony';

export const DEMO_MATRIMONY_PROFILES: MatrimonyProfile[] = [
  {
    id: '1',
    name: 'Priya Shah',
    age: 26,
    gender: 'female',
    dateOfBirth: '1998-07-15',
    height: "5'4\"",
    weight: '55 kg',
    complexion: 'Fair',
    bloodGroup: 'B+',
    maritalStatus: 'Never Married',
    diet: 'Jain',
    language: 'Gujarati',
    sect: 'Shwetambar',
    caste: 'Oswal',
    gotra: 'Porwal',
    education: { highest: 'MBA', degree: 'MBA - Finance', college: 'IIM Ahmedabad' },
    work: { occupation: 'Bank Manager', company: 'HDFC Bank', location: 'Surat', incomeRange: '10-15 LPA' },
    city: 'Surat',
    nativePlace: { paternal: { city: 'Palanpur', state: 'Gujarat' }, maternal: { city: 'Ahmedabad', state: 'Gujarat' } },
    family: {
      fatherName: 'Kantilal Shah',
      fatherOccupation: 'Diamond Merchant',
      motherName: 'Pushpaben Shah',
      motherOccupation: 'Homemaker',
      siblings: [{ relation: 'Brother', maritalStatus: 'Married', details: 'Chartered Accountant' }],
      familyType: 'Nuclear',
      about: 'Well-known Jain family from Palanpur settled in Surat. Active in Jain Sangh.',
    },
    mamaji: [{ name: 'Sureshbhai Mehta', currentCity: 'Ahmedabad', nativePlace: { city: 'Mehsana', state: 'Gujarat' }, occupation: 'Business' }],
    buva: [{ name: 'Prabhaben Jain', currentCity: 'Mumbai', nativePlace: { city: 'Palanpur', state: 'Gujarat' }, occupation: 'Homemaker' }],
    dharmik: {
      routine: ['samayik', 'pratikraman', 'swadhyay'],
      knowledgeLevel: 'advanced',
      pathshala: { attended: true, years: 8 },
      seva: ['volunteer', 'teaching'],
    },
    tap: {
      types: ['upvas', 'ekasana', 'ayambil'],
      lifetimeCounts: { upvas: 200, ayambil: 48, ekasana: 300 },
      recent12Months: { upvas: 24, ayambil: 8 },
      biggestTap: 'Varshitap (13 months)',
    },
    partnerPrefs: {
      ageRange: { min: 27, max: 32 },
      heightRange: { min: "5'7\"", max: "6'2\"" },
      cityPreference: ['Surat', 'Ahmedabad', 'Mumbai'],
      sectPreference: 'Shwetambar',
      educationPreference: 'Graduate or above',
      dharmikPreference: 'Regular Samayik & Pratikraman',
    },
    about: 'Simple, family-oriented girl. Completed Varshitap. Looking for a compatible dharmik life partner.',
    isVerified: true,
    verificationLevel: 'community',
    isPremium: true,
    photos: [],
  },
  {
    id: '2',
    name: 'Rahul Jain',
    age: 28,
    gender: 'male',
    dateOfBirth: '1996-03-20',
    height: "5'10\"",
    complexion: 'Wheatish',
    bloodGroup: 'O+',
    maritalStatus: 'Never Married',
    diet: 'Jain',
    language: 'Hindi',
    sect: 'Digambar',
    caste: 'Agarwal',
    gotra: 'Bansal',
    education: { highest: 'B.Tech', degree: 'B.Tech - Computer Science', college: 'NIT Surat' },
    work: { occupation: 'Software Engineer', company: 'Google India', location: 'Bangalore', incomeRange: '25-30 LPA' },
    city: 'Bangalore',
    nativePlace: { paternal: { city: 'Jaipur', state: 'Rajasthan' }, maternal: { city: 'Udaipur', state: 'Rajasthan' } },
    family: {
      fatherName: 'Ramesh Jain',
      fatherOccupation: 'Businessman',
      motherName: 'Sunita Jain',
      motherOccupation: 'Teacher',
      siblings: [{ relation: 'Sister', maritalStatus: 'Married', details: 'Doctor' }],
      familyType: 'Joint',
      about: 'Traditional Jain family with strong values.',
    },
    mamaji: [{ name: 'Maheshbhai Gupta', currentCity: 'Udaipur', nativePlace: { city: 'Udaipur', state: 'Rajasthan' }, occupation: 'Jeweller' }],
    buva: [],
    dharmik: {
      routine: ['swadhyay', 'dev-darshan'],
      knowledgeLevel: 'intermediate',
      pathshala: { attended: true, years: 5 },
      seva: ['donation'],
    },
    tap: {
      types: ['upvas', 'ekasana'],
      lifetimeCounts: { upvas: 50, ayambil: 0, ekasana: 80 },
      recent12Months: { upvas: 12, ayambil: 0 },
      biggestTap: 'Atthai (8 days)',
    },
    partnerPrefs: {
      ageRange: { min: 23, max: 28 },
      heightRange: { min: "5'0\"", max: "5'6\"" },
      cityPreference: ['Bangalore', 'Mumbai', 'Pune'],
      sectPreference: 'Digambar',
      educationPreference: 'Graduate',
      dharmikPreference: 'Basic practices',
    },
    about: 'Working in a top IT company. Looking for an educated life partner who values Jain traditions.',
    isVerified: true,
    verificationLevel: 'id',
    isPremium: false,
    photos: [],
  },
  {
    id: '3',
    name: 'Anita Mehta',
    age: 24,
    gender: 'female',
    dateOfBirth: '2000-11-08',
    height: "5'3\"",
    complexion: 'Fair',
    bloodGroup: 'A+',
    maritalStatus: 'Never Married',
    diet: 'Jain',
    language: 'Gujarati',
    sect: 'Shwetambar',
    caste: 'Oswal',
    education: { highest: 'CA', degree: 'Chartered Accountant', college: 'ICAI' },
    work: { occupation: 'CA', company: 'Deloitte', location: 'Mumbai', incomeRange: '12-18 LPA' },
    city: 'Mumbai',
    nativePlace: { paternal: { city: 'Rajkot', state: 'Gujarat' }, maternal: { city: 'Jamnagar', state: 'Gujarat' } },
    family: {
      fatherName: 'Dilipbhai Mehta',
      fatherOccupation: 'Textile Business',
      motherName: 'Hemlataben Mehta',
      motherOccupation: 'Homemaker',
      siblings: [],
      familyType: 'Nuclear',
      about: 'Small, close-knit family with strong Jain values.',
    },
    mamaji: [],
    buva: [],
    dharmik: {
      routine: ['samayik', 'dev-darshan'],
      knowledgeLevel: 'intermediate',
      pathshala: { attended: true, years: 6 },
      seva: ['volunteer'],
    },
    tap: {
      types: ['upvas'],
      lifetimeCounts: { upvas: 60, ayambil: 0, ekasana: 40 },
      recent12Months: { upvas: 8, ayambil: 0 },
      biggestTap: 'Navpad Oli (9 days)',
    },
    partnerPrefs: {
      ageRange: { min: 25, max: 30 },
      cityPreference: ['Mumbai', 'Pune', 'Ahmedabad'],
      sectPreference: 'Shwetambar',
      educationPreference: 'CA/MBA/Professional',
    },
    about: 'Professionally qualified CA. Looking for someone with similar values and ambitions.',
    isVerified: false,
    verificationLevel: 'basic',
    isPremium: false,
    photos: [],
  },
  {
    id: '4',
    name: 'Vikram Shah',
    age: 30,
    gender: 'male',
    dateOfBirth: '1994-01-22',
    height: "5'8\"",
    complexion: 'Fair',
    bloodGroup: 'AB+',
    maritalStatus: 'Never Married',
    diet: 'Jain',
    language: 'Gujarati',
    sect: 'Shwetambar',
    caste: 'Oswal',
    gotra: 'Oswal',
    education: { highest: 'MD', degree: 'MD Medicine', college: 'AIIMS Delhi' },
    work: { occupation: 'Doctor', company: 'Apollo Hospital', location: 'Rajkot', incomeRange: '20-30 LPA' },
    city: 'Rajkot',
    nativePlace: { paternal: { city: 'Rajkot', state: 'Gujarat' }, maternal: { city: 'Surat', state: 'Gujarat' } },
    family: {
      fatherName: 'Dr. Hareshbhai Shah',
      fatherOccupation: 'Senior Doctor',
      motherName: 'Kokilaben Shah',
      motherOccupation: 'Homemaker',
      siblings: [{ relation: 'Brother', maritalStatus: 'Unmarried', details: 'MBA Student' }],
      familyType: 'Joint',
      about: 'Well-respected medical family in Rajkot with deep Jain roots.',
    },
    mamaji: [{ name: 'Jayeshbhai Doshi', currentCity: 'Surat', nativePlace: { city: 'Surat', state: 'Gujarat' }, occupation: 'Diamond Business' }],
    buva: [{ name: 'Sangeetaben Kothari', currentCity: 'Ahmedabad', nativePlace: { city: 'Rajkot', state: 'Gujarat' }, occupation: 'Homemaker' }],
    dharmik: {
      routine: ['samayik', 'pratikraman', 'swadhyay', 'dev-darshan'],
      knowledgeLevel: 'advanced',
      pathshala: { attended: true, years: 10 },
      seva: ['volunteer', 'donation', 'teaching'],
    },
    tap: {
      types: ['upvas', 'ekasana', 'ayambil'],
      lifetimeCounts: { upvas: 300, ayambil: 60, ekasana: 500 },
      recent12Months: { upvas: 36, ayambil: 16 },
      biggestTap: 'Varshitap (13 months)',
    },
    partnerPrefs: {
      ageRange: { min: 24, max: 28 },
      heightRange: { min: "5'2\"", max: "5'6\"" },
      cityPreference: ['Rajkot', 'Ahmedabad', 'Surat'],
      sectPreference: 'Shwetambar',
      educationPreference: 'Graduate or above',
      dharmikPreference: 'Strong dharmik family with regular Tap',
    },
    about: 'AIIMS qualified doctor. Completed Varshitap. Looking for a dharmik, educated partner.',
    isVerified: true,
    verificationLevel: 'community',
    isPremium: true,
    photos: [],
  },
];
