import { NewsArticle, NewsComment } from '../types/news';

export const DEMO_NEWS: NewsArticle[] = [
  {
    id: '1',
    title: 'Paryushan Mahaparva 2026 Dates Announced',
    titleGu: 'પર્યુષણ મહાપર્વ ૨૦૨૬ ની તારીખો જાહેર',
    summary: 'The holy festival of Paryushan will be observed from August 21-28 this year. Sangh committees across India have started preparations.',
    content: 'The Shwetambar Jain community will observe Paryushan Mahaparva from August 21 to August 28, 2026. Das Lakshan Parva for Digambar tradition will follow from August 28 to September 6.\n\nSangh committees across major cities have already begun preparations for the eight-day festival. Special arrangements for bhakti, tap, and seva activities are being planned.\n\nKey highlights:\n- Pratikraman sessions twice daily\n- Special pravachan by renowned Maharaj Saheb\n- Community bhojan arrangements\n- Tap support for fasting devotees\n- Michhami Dukkadam celebrations on final day',
    imageUrl: undefined,
    category: 'events',
    author: 'JainSetu Team',
    publishedAt: '2026-02-19',
    isVerified: true,
    isBreaking: true,
    reactions: [
      { code: 'LIKE', emoji: '👍', label: 'Like', count: 1245 },
      { code: 'NAMASTE', emoji: '🙏', label: 'Namaste', count: 823 },
      { code: 'HAPPY', emoji: '😀', label: 'Happy', count: 456 },
      { code: 'THANKYOU', emoji: '💐', label: 'Thank You', count: 120 },
      { code: 'CRYING', emoji: '😢', label: 'Crying', count: 15 },
    ],
    commentsCount: 89,
    sharesCount: 312,
  },
  {
    id: '2',
    title: 'New Jain Temple Inaugurated in Surat',
    titleGu: 'સુરતમાં નવું જૈન મંદિર ખુલ્લું મુકાયું',
    summary: 'A magnificent new Jain Derasar with 24 Tirthankar idols was inaugurated in Vesu area of Surat with grand celebrations.',
    content: 'A beautifully crafted new Jain Derasar has been inaugurated in the Vesu area of Surat. The temple features 24 Tirthankar idols carved from Makrana marble.\n\nThe inauguration ceremony was attended by over 5,000 devotees and was graced by Acharya Shri Chandanasagarji Maharaj Saheb.\n\nThe temple complex includes:\n- Main prayer hall with all 24 Tirthankar idols\n- Meditation center\n- Community hall for 500+ people\n- Library with rare Jain manuscripts\n- Bhojanshala for 200 people',
    imageUrl: undefined,
    category: 'community',
    author: 'Surat Jain Sangh',
    publishedAt: '2026-02-18',
    isVerified: true,
    reactions: [
      { code: 'LIKE', emoji: '👍', label: 'Like', count: 2100 },
      { code: 'NAMASTE', emoji: '🙏', label: 'Namaste', count: 1500 },
      { code: 'HAPPY', emoji: '😀', label: 'Happy', count: 890 },
      { code: 'THANKYOU', emoji: '💐', label: 'Thank You', count: 345 },
      { code: 'CRYING', emoji: '😢', label: 'Crying', count: 0 },
    ],
    commentsCount: 156,
    sharesCount: 523,
  },
  {
    id: '3',
    title: 'Palitana Yatra Season Begins with Record Pilgrims',
    titleGu: 'પાલિતાણા યાત્રા સીઝન રેકોર્ડ યાત્રિકો સાથે શરૂ',
    summary: 'Over 50,000 pilgrims visited Shatrunjay Hill in the first week of the season, setting a new record for the temple trust.',
    content: 'The pilgrimage season at Palitana has begun with unprecedented enthusiasm. Over 50,000 devotees climbed the sacred Shatrunjay Hill in the very first week.\n\nNew facilities added this year include:\n- Electric vehicle service to the base\n- Improved resting shelters every 500 steps\n- Free water and medical aid stations\n- Digital darshan booking for senior citizens',
    imageUrl: undefined,
    category: 'spiritual',
    author: 'Palitana Temple Trust',
    publishedAt: '2026-02-17',
    isVerified: true,
    reactions: [
      { code: 'LIKE', emoji: '👍', label: 'Like', count: 3200 },
      { code: 'NAMASTE', emoji: '🙏', label: 'Namaste', count: 2100 },
      { code: 'HAPPY', emoji: '😀', label: 'Happy', count: 1200 },
      { code: 'THANKYOU', emoji: '💐', label: 'Thank You', count: 560 },
      { code: 'CRYING', emoji: '😢', label: 'Crying', count: 23 },
    ],
    commentsCount: 234,
    sharesCount: 890,
  },
  {
    id: '4',
    title: 'Jain Youth Federation Launches Skill Development Program',
    titleGu: 'જૈન યુવા ફેડરેશન દ્વારા કૌશલ્ય વિકાસ કાર્યક્રમ શરૂ',
    summary: 'Free IT, business, and spoken English courses for Jain youth launched in 12 cities with placement guarantee.',
    content: 'The All India Jain Youth Federation has launched a nationwide Skill Development Program targeting youth aged 18-30. The program offers free courses in:\n\n1. Information Technology (Web, Mobile, AI)\n2. Business & Entrepreneurship\n3. Spoken English & Communication\n4. Digital Marketing\n5. Accounting & Finance\n\nClasses will be held in 12 cities initially: Mumbai, Surat, Ahmedabad, Delhi, Jaipur, Bangalore, Pune, Indore, Kolkata, Chennai, Hyderabad, and Udaipur.',
    imageUrl: undefined,
    category: 'education',
    author: 'Jain Youth Federation',
    publishedAt: '2026-02-16',
    isVerified: true,
    reactions: [
      { code: 'LIKE', emoji: '👍', label: 'Like', count: 890 },
      { code: 'NAMASTE', emoji: '🙏', label: 'Namaste', count: 234 },
      { code: 'HAPPY', emoji: '😀', label: 'Happy', count: 567 },
      { code: 'THANKYOU', emoji: '💐', label: 'Thank You', count: 189 },
      { code: 'CRYING', emoji: '😢', label: 'Crying', count: 5 },
    ],
    commentsCount: 78,
    sharesCount: 234,
  },
  {
    id: '5',
    title: 'Government Recognizes Jain Community Contribution to Education',
    summary: 'The Ministry of Education has recognized the Jain community for running over 5,000 educational institutions across India serving 2 million students.',
    content: 'In a historic move, the Government of India has officially recognized the massive contribution of the Jain community to Indian education. With over 5,000 schools, colleges, and universities, the community serves nearly 2 million students across the country.\n\nThe recognition comes with a special award that will be presented during Republic Day celebrations.',
    imageUrl: undefined,
    category: 'national',
    author: 'JainSetu News',
    publishedAt: '2026-02-15',
    isVerified: true,
    reactions: [
      { code: 'LIKE', emoji: '👍', label: 'Like', count: 4500 },
      { code: 'NAMASTE', emoji: '🙏', label: 'Namaste', count: 1800 },
      { code: 'HAPPY', emoji: '😀', label: 'Happy', count: 2300 },
      { code: 'THANKYOU', emoji: '💐', label: 'Thank You', count: 890 },
      { code: 'CRYING', emoji: '😢', label: 'Crying', count: 45 },
    ],
    commentsCount: 312,
    sharesCount: 1200,
  },
  {
    id: '6',
    title: 'Acharya Shri Chandrasagarji Maharaj Chaturmas in Ahmedabad',
    titleGu: 'આચાર્ય શ્રી ચંદ્રસાગરજી મહારાજ સાહેબનું ચાતુર્માસ અમદાવાદમાં',
    summary: 'The revered Acharya Shri has announced Chaturmas in Ahmedabad this year. Thousands expected to attend the 4-month spiritual retreat.',
    content: 'Acharya Shri Chandrasagarji Maharaj Saheb has announced that this year\'s Chaturmas will be held at Shri Jain Shwetambar Sangh, Paldi, Ahmedabad.\n\nThe four-month spiritual retreat will include:\n- Daily pravachan at 8:30 AM and 5:00 PM\n- Weekly special swadhyay sessions\n- Youth interaction programs every Saturday\n- Tap guidance and support\n- Special Paryushan celebrations',
    imageUrl: undefined,
    category: 'spiritual',
    author: 'Ahmedabad Jain Sangh',
    publishedAt: '2026-02-14',
    isVerified: true,
    reactions: [
      { code: 'LIKE', emoji: '👍', label: 'Like', count: 1890 },
      { code: 'NAMASTE', emoji: '🙏', label: 'Namaste', count: 3200 },
      { code: 'HAPPY', emoji: '😀', label: 'Happy', count: 780 },
      { code: 'THANKYOU', emoji: '💐', label: 'Thank You', count: 456 },
      { code: 'CRYING', emoji: '😢', label: 'Crying', count: 12 },
    ],
    commentsCount: 189,
    sharesCount: 678,
  },
];

export const DEMO_NEWS_COMMENTS: NewsComment[] = [
  { id: '1', userId: '1', userName: 'Rajesh Shah', text: 'Jai Jinendra! This is wonderful news. Looking forward to Paryushan.', likesCount: 24, createdAt: '2026-02-19' },
  { id: '2', userId: '2', userName: 'Nidhi Jain', text: 'Our whole family is planning to attend this year!', likesCount: 15, createdAt: '2026-02-19', replies: [
    { id: '2a', userId: '3', userName: 'Amit Mehta', text: 'Same here! See you there.', parentCommentId: '2', likesCount: 5, createdAt: '2026-02-19' },
  ] },
  { id: '3', userId: '4', userName: 'Priya Shah', text: 'Michhami Dukkadam to all in advance!', likesCount: 42, createdAt: '2026-02-18' },
  { id: '4', userId: '5', userName: 'Vikram Jain', text: 'Can someone share the schedule for Surat?', likesCount: 8, createdAt: '2026-02-18' },
];
