import { TirthListing, DailyMenu, RoomType } from '../types/tirth';

export const DEMO_TIRTH_LISTINGS: TirthListing[] = [
  {
    id: '1',
    tirthId: 't1',
    category: 'tirth',
    name: 'Palitana Shatrunjaya',
    nameGuj: 'પાલિતાણા શત્રુંજય',
    address: 'Shatrunjaya Hill, Palitana',
    city: 'Bhavnagar',
    state: 'Gujarat',
    lat: 21.5229,
    lng: 71.8217,
    description: 'The holiest pilgrimage place for Jains with 863 temples on Shatrunjaya Hill.',
    facilities: ['Dharamshala', 'Bhojanshala', 'Medical', 'Parking', 'Doli Service', 'Shoe Storage'],
    timings: { darshan: '6:00 AM - 6:30 PM', bhojan: '11:00 AM - 1:00 PM' },
    rules: 'No leather items. Modest dress code. No food on the hill.',
    isVerified: true,
    rating: 4.9,
    reviewCount: 2500,
    contacts: [
      { personName: 'Trust Office', phone1: '02848-252252', whatsapp: '9876543210', visibility: 'public' },
    ],
    photos: [],
    roomAvailability: 'available',
    hasMenu: true,
    nearestRailway: 'Palitana Railway Station (2 km)',
    nearestAirport: 'Bhavnagar Airport (55 km)',
  },
  {
    id: '2',
    tirthId: 't1',
    category: 'dharamshala',
    name: 'Shri Palitana Jain Dharamshala',
    nameGuj: 'શ્રી પાલિતાણા જૈન ધર્મશાળા',
    address: 'Near Taleti, Palitana',
    city: 'Bhavnagar',
    state: 'Gujarat',
    lat: 21.5250,
    lng: 71.8200,
    description: 'Modern dharamshala with AC and non-AC rooms for pilgrims visiting Shatrunjaya.',
    facilities: ['AC Rooms', 'Non-AC Rooms', 'Bhojanshala', 'Parking', 'WiFi', 'Hot Water', 'Lift'],
    timings: { checkIn: '12:00 PM', checkOut: '11:00 AM' },
    rules: 'Valid ID proof required. Jain food only. No smoking.',
    isVerified: true,
    rating: 4.5,
    reviewCount: 890,
    contacts: [
      { personName: 'Booking Office', phone1: '02848-253000', whatsapp: '9876543211', visibility: 'public' },
    ],
    photos: [],
    roomAvailability: 'limited',
    hasMenu: true,
  },
  {
    id: '3',
    tirthId: undefined,
    category: 'bhojanshala',
    name: 'Shri Jain Bhojanshala Surat',
    nameGuj: 'શ્રી જૈન ભોજનશાળા સુરત',
    address: 'Ring Road, Surat',
    city: 'Surat',
    state: 'Gujarat',
    lat: 21.1702,
    lng: 72.8311,
    description: 'Daily Jain bhojan available. Satvik food prepared with pure ingredients.',
    facilities: ['Jain Food', 'Aayambil', 'Token System', 'Parking'],
    timings: { breakfast: '8:00 AM - 9:30 AM', lunch: '11:30 AM - 1:30 PM', dinner: '7:00 PM - 9:00 PM' },
    rules: 'Token system for meals. Donation based.',
    isVerified: true,
    rating: 4.7,
    reviewCount: 450,
    contacts: [
      { personName: 'Manager', phone1: '0261-2435000', visibility: 'public' },
    ],
    photos: [],
    roomAvailability: undefined,
    hasMenu: true,
  },
  {
    id: '4',
    tirthId: undefined,
    category: 'upashray',
    name: 'Shri Jain Upashray Ahmedabad',
    nameGuj: 'શ્રી જૈન ઉપાશ્રય અમદાવાદ',
    address: 'Paldi, Ahmedabad',
    city: 'Ahmedabad',
    state: 'Gujarat',
    lat: 23.0225,
    lng: 72.5714,
    description: 'Sacred upashray for sadhus and sadhvis. Community programs held regularly.',
    facilities: ['Upashray Hall', 'Swadhyay Room', 'Medical Aid'],
    timings: { morning: '6:00 AM - 8:00 AM', evening: '4:00 PM - 7:00 PM' },
    isVerified: true,
    rating: 4.8,
    reviewCount: 320,
    contacts: [
      { personName: 'Sangh Office', phone1: '079-26570000', visibility: 'public' },
    ],
    photos: [],
  },
  {
    id: '5',
    tirthId: undefined,
    category: 'temple',
    name: 'Ranakpur Jain Temple',
    nameGuj: 'રાણકપુર જૈન મંદિર',
    address: 'Ranakpur, Pali',
    city: 'Pali',
    state: 'Rajasthan',
    lat: 25.1156,
    lng: 73.4700,
    description: 'Famous for its marble architecture with 1444 uniquely carved pillars.',
    facilities: ['Dharamshala', 'Bhojanshala', 'Guide Service', 'Parking', 'Wheelchair Access'],
    timings: { darshan: '7:00 AM - 5:00 PM', bhojan: '11:00 AM - 1:00 PM' },
    rules: 'Photography not allowed inside main temple. Modest dress code.',
    isVerified: true,
    rating: 4.8,
    reviewCount: 1800,
    contacts: [
      { personName: 'Trust Office', phone1: '02934-285025', visibility: 'public' },
    ],
    photos: [],
    roomAvailability: 'available',
    hasMenu: true,
    nearestRailway: 'Falna Railway Station (35 km)',
    nearestAirport: 'Udaipur Airport (96 km)',
  },
  {
    id: '6',
    tirthId: undefined,
    category: 'ayambil',
    name: 'Shri Ayambil Shala Rajkot',
    nameGuj: 'શ્રી આયંબિલ શાળા રાજકોટ',
    address: 'Kalavad Road, Rajkot',
    city: 'Rajkot',
    state: 'Gujarat',
    lat: 22.3039,
    lng: 70.8022,
    description: 'Dedicated Ayambil Shala serving pure ayambil food during Oli and year-round.',
    facilities: ['Ayambil Food', 'Sitting Area', 'Water'],
    timings: { ayambil: '10:00 AM - 12:00 PM' },
    rules: 'Ayambil food only. No salt, no oil, no sugar.',
    isVerified: true,
    rating: 4.6,
    reviewCount: 180,
    contacts: [
      { personName: 'Coordinator', phone1: '9876543215', visibility: 'public' },
    ],
    photos: [],
    hasMenu: true,
  },
  {
    id: '7',
    tirthId: undefined,
    category: 'tirth',
    name: 'Shikharji',
    nameGuj: 'શિખરજી',
    address: 'Parasnath Hills, Giridih',
    city: 'Giridih',
    state: 'Jharkhand',
    lat: 23.9629,
    lng: 86.1361,
    description: 'Supreme pilgrimage for Jains, where 20 Tirthankaras attained Nirvana.',
    facilities: ['Dharamshala', 'Bhojanshala', 'Doli Service', 'Medical', 'Parking'],
    timings: { darshan: '4:00 AM - 6:00 PM' },
    rules: 'Carry warm clothing. Trek is 28 km round trip.',
    isVerified: true,
    rating: 4.9,
    reviewCount: 3200,
    contacts: [
      { personName: 'Trust Office', phone1: '06532-222222', visibility: 'public' },
    ],
    photos: [],
    roomAvailability: 'available',
    hasMenu: true,
    nearestRailway: 'Parasnath Railway Station (22 km)',
    nearestAirport: 'Ranchi Airport (170 km)',
  },
  {
    id: '8',
    tirthId: undefined,
    category: 'gharDerasar',
    name: 'Ghar Derasar - Shah Family',
    nameGuj: 'ઘર દેરાસર - શાહ ફેમિલી',
    address: 'Varachha Road, Surat',
    city: 'Surat',
    state: 'Gujarat',
    lat: 21.2000,
    lng: 72.8500,
    description: 'Beautiful private derasar open for community darshan on Parva days.',
    facilities: ['Darshan', 'Parking'],
    timings: { darshan: '6:00 AM - 8:00 AM, 5:00 PM - 7:00 PM' },
    isVerified: false,
    rating: 4.4,
    reviewCount: 45,
    contacts: [],
    photos: [],
  },
];

export const DEMO_DAILY_MENUS: DailyMenu[] = [
  {
    id: 'm1',
    listingId: '3',
    date: new Date().toISOString().split('T')[0],
    breakfast: 'Poha, Upma, Chai',
    lunch: 'Dal, Rice, Roti, Sabzi, Salad, Papad',
    dinner: 'Khichdi, Kadhi, Roti, Sabzi',
    ayambil: 'Bajra Rotla, Moong Dal (no oil/salt)',
    price: 'Donation basis',
    timings: { breakfast: '8:00 AM', lunch: '11:30 AM', dinner: '7:00 PM' },
  },
];

export const DEMO_ROOM_TYPES: RoomType[] = [
  { id: 'r1', listingId: '2', typeName: 'AC Deluxe', beds: 2, basePrice: 500, totalRooms: 20, availableRooms: 8 },
  { id: 'r2', listingId: '2', typeName: 'Non-AC', beds: 2, basePrice: 200, totalRooms: 30, availableRooms: 15 },
  { id: 'r3', listingId: '2', typeName: 'Dormitory', beds: 10, basePrice: 50, totalRooms: 5, availableRooms: 3 },
];
